package com.computerstore.email;

public enum OrderEmailEventType {
    ORDER_CREATED,
    PAYMENT_APPROVED,
    BANK_TRANSFER_REJECTED,
    ORDER_CANCELLED,
    PAYMENT_REFUNDED,
    ORDER_DELIVERED,
    SHIPMENT_TRACKING_AVAILABLE,
    SELLER_ORDER_CREATED,
    SELLER_PAYMENT_APPROVED
}
