ALTER TABLE product_images
    ADD COLUMN storage_key VARCHAR(36),
    ADD COLUMN original_filename VARCHAR(255),
    ADD COLUMN content_type VARCHAR(50),
    ADD COLUMN size_bytes BIGINT,
    ADD COLUMN created_at TIMESTAMPTZ;

ALTER TABLE product_images
    ADD CONSTRAINT uq_product_images_storage_key UNIQUE (storage_key),
    ADD CONSTRAINT chk_product_images_storage_metadata CHECK (
        (storage_key IS NULL AND original_filename IS NULL AND content_type IS NULL AND size_bytes IS NULL AND created_at IS NULL)
        OR
        (storage_key IS NOT NULL AND original_filename IS NOT NULL AND content_type IN ('image/jpeg', 'image/png')
            AND size_bytes > 0 AND created_at IS NOT NULL)
    );

CREATE TABLE ticket_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES technical_service_tickets(id) ON DELETE RESTRICT,
    uploaded_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    uploader_role VARCHAR(20) NOT NULL,
    storage_key VARCHAR(36) NOT NULL UNIQUE,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_ticket_attachments_size CHECK (size_bytes > 0),
    CONSTRAINT chk_ticket_attachments_content_type CHECK (content_type IN ('image/jpeg', 'image/png')),
    CONSTRAINT chk_ticket_attachments_role CHECK (uploader_role IN ('CUSTOMER', 'TECHNICIAN', 'ADMIN'))
);

CREATE INDEX idx_ticket_attachments_ticket_id ON ticket_attachments(ticket_id);
CREATE INDEX idx_ticket_attachments_uploaded_by ON ticket_attachments(uploaded_by_user_id);
CREATE INDEX idx_ticket_attachments_ticket_created ON ticket_attachments(ticket_id, created_at);
