LOCK TABLE products, inventory, order_items, inventory_movements IN SHARE ROW EXCLUSIVE MODE;

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    color_name VARCHAR(100) NOT NULL,
    color_hex VARCHAR(7),
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_product_variants_color_name CHECK (BTRIM(color_name) <> ''),
    CONSTRAINT chk_product_variants_color_hex CHECK (color_hex IS NULL OR color_hex ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT chk_product_variants_display_order CHECK (display_order >= 0)
);

CREATE INDEX idx_product_variants_product ON product_variants(product_id, display_order, id);
CREATE UNIQUE INDEX uq_product_variants_product_color ON product_variants(product_id, LOWER(color_name)) WHERE is_active;

INSERT INTO product_variants(product_id, color_name, display_order)
SELECT id, 'Unico', 0 FROM products;

INSERT INTO inventory(product_id, available_quantity, reserved_quantity, updated_at)
SELECT product.id, 0, 0, CURRENT_TIMESTAMP
FROM products product
WHERE NOT EXISTS (SELECT 1 FROM inventory WHERE inventory.product_id = product.id);

ALTER TABLE inventory ADD COLUMN variant_id BIGINT;
ALTER TABLE order_items ADD COLUMN variant_id BIGINT, ADD COLUMN variant_color_name VARCHAR(100), ADD COLUMN variant_color_hex VARCHAR(7);
ALTER TABLE inventory_movements ADD COLUMN variant_id BIGINT;

UPDATE inventory SET variant_id = variant.id FROM product_variants variant WHERE variant.product_id = inventory.product_id;
UPDATE order_items SET variant_id = variant.id, variant_color_name = variant.color_name, variant_color_hex = variant.color_hex FROM product_variants variant WHERE variant.product_id = order_items.product_id;
UPDATE inventory_movements SET variant_id = variant.id FROM product_variants variant WHERE variant.product_id = inventory_movements.product_id;

ALTER TABLE inventory DROP CONSTRAINT inventory_pkey;
ALTER TABLE inventory ALTER COLUMN variant_id SET NOT NULL, ADD CONSTRAINT inventory_pkey PRIMARY KEY (variant_id), ADD CONSTRAINT fk_inventory_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT;
ALTER TABLE order_items ALTER COLUMN variant_id SET NOT NULL, ALTER COLUMN variant_color_name SET NOT NULL, ADD CONSTRAINT fk_order_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT;
ALTER TABLE inventory_movements ALTER COLUMN variant_id SET NOT NULL, ADD CONSTRAINT fk_inventory_movements_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT;

ALTER TABLE inventory DROP COLUMN product_id;
ALTER TABLE order_items DROP COLUMN product_id;
ALTER TABLE inventory_movements DROP COLUMN product_id;

CREATE INDEX idx_order_items_variant ON order_items(variant_id);
CREATE INDEX idx_inventory_movements_variant ON inventory_movements(variant_id);
