ALTER TABLE users
    ALTER COLUMN password_hash DROP NOT NULL,
    ADD COLUMN email_verified_at TIMESTAMPTZ,
    ADD COLUMN session_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));

CREATE TABLE user_addresses (
    user_id BIGINT PRIMARY KEY,
    street VARCHAR(150) NOT NULL,
    street_number VARCHAR(30) NOT NULL,
    floor_apartment VARCHAR(50),
    locality VARCHAR(120) NOT NULL,
    province_code VARCHAR(3) NOT NULL,
    postal_code VARCHAR(12) NOT NULL,
    country_code VARCHAR(2) NOT NULL DEFAULT 'AR',
    reference VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_addresses_province_code CHECK (province_code ~ '^[A-Z]{1,3}$'),
    CONSTRAINT chk_user_addresses_country_code CHECK (country_code ~ '^[A-Z]{2}$')
);

CREATE TABLE account_action_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    target_email VARCHAR(254),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_account_action_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_account_action_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_account_action_tokens_purpose CHECK (purpose IN (
        'EMAIL_VERIFICATION', 'PASSWORD_RESET', 'EMAIL_CHANGE'
    )),
    CONSTRAINT chk_account_action_tokens_target CHECK (
        (purpose = 'EMAIL_CHANGE' AND target_email IS NOT NULL)
        OR (purpose <> 'EMAIL_CHANGE' AND target_email IS NULL)
    )
);

CREATE INDEX idx_account_action_tokens_user_purpose
    ON account_action_tokens (user_id, purpose);
CREATE INDEX idx_account_action_tokens_expires_at
    ON account_action_tokens (expires_at);

CREATE TABLE user_external_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    observed_email VARCHAR(254),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_external_identities_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_external_identities_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uq_user_external_identities_user_provider UNIQUE (user_id, provider),
    CONSTRAINT chk_user_external_identities_provider CHECK (provider IN ('GOOGLE'))
);

CREATE INDEX idx_user_external_identities_user_id
    ON user_external_identities (user_id);
