ALTER TABLE refresh_tokens
    ADD COLUMN session_version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE google_auth_nonces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nonce_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_google_auth_nonces_hash UNIQUE (nonce_hash)
);

CREATE INDEX idx_google_auth_nonces_expires_at
    ON google_auth_nonces (expires_at);
CREATE INDEX idx_google_auth_nonces_active
    ON google_auth_nonces (nonce_hash) WHERE consumed_at IS NULL;
