ALTER TABLE customer_orders
    ADD COLUMN payment_surcharge NUMERIC(19, 2) NOT NULL DEFAULT 0 CHECK (payment_surcharge >= 0),
    ADD COLUMN payment_due_at TIMESTAMPTZ,
    ADD COLUMN bank_holder VARCHAR(150),
    ADD COLUMN bank_tax_id VARCHAR(30),
    ADD COLUMN bank_name VARCHAR(150),
    ADD COLUMN bank_alias VARCHAR(100),
    ADD COLUMN bank_cbu VARCHAR(22),
    ADD COLUMN bank_currency VARCHAR(3);

UPDATE customer_orders SET payment_method = 'MERCADO_PAGO' WHERE payment_method IS NULL;

-- Keep inserts from the previous application version valid while a rolling deployment drains it.
CREATE FUNCTION default_customer_order_payment_method() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.payment_method IS NULL THEN
        NEW.payment_method := 'MERCADO_PAGO';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_customer_orders_default_payment_method
    BEFORE INSERT ON customer_orders
    FOR EACH ROW EXECUTE FUNCTION default_customer_order_payment_method();

ALTER TABLE customer_orders
    ALTER COLUMN payment_method SET NOT NULL,
    ALTER COLUMN reservation_expires_at DROP NOT NULL,
    DROP CONSTRAINT chk_customer_orders_payment_status,
    ADD CONSTRAINT chk_customer_orders_payment_status CHECK (payment_status IN (
        'PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED',
        'REFUND_PENDING', 'REFUNDED', 'IN_MEDIATION', 'CHARGEBACK'
    )),
    ADD CONSTRAINT chk_customer_orders_payment_method CHECK (
        payment_method IN ('BANK_TRANSFER', 'MERCADO_PAGO')
    ),
    ADD CONSTRAINT chk_customer_orders_bank_snapshot CHECK (
        (payment_method = 'MERCADO_PAGO' AND payment_due_at IS NULL
            AND bank_holder IS NULL AND bank_tax_id IS NULL AND bank_name IS NULL
            AND bank_alias IS NULL AND bank_cbu IS NULL AND bank_currency IS NULL)
        OR
        (payment_method = 'BANK_TRANSFER' AND payment_due_at IS NOT NULL
            AND bank_holder IS NOT NULL AND bank_tax_id IS NOT NULL AND bank_name IS NOT NULL
            AND bank_alias IS NOT NULL AND bank_cbu IS NOT NULL AND bank_currency = currency)
    );

CREATE UNIQUE INDEX uq_customer_orders_one_pending_transfer_per_user
    ON customer_orders(user_id)
    WHERE status = 'PENDING_PAYMENT' AND payment_method = 'BANK_TRANSFER';

CREATE TABLE bank_transfer_proofs (
    id UUID PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES customer_orders(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    storage_key VARCHAR(36),
    original_filename VARCHAR(255),
    content_type VARCHAR(100),
    size_bytes BIGINT CHECK (size_bytes > 0 AND size_bytes <= 5242880),
    sha256 VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(100),
    submitted_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    approved_amount NUMERIC(19, 2),
    reviewed_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    rejection_reason VARCHAR(1000),
    bank_reference VARCHAR(100),
    retain_until TIMESTAMPTZ,
    file_deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_bank_transfer_proof_reference CHECK (
        bank_reference IS NULL OR bank_reference ~ '^[A-Z0-9]{6,100}$'
    ),
    CONSTRAINT chk_bank_transfer_proof_status CHECK (
        status IN ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'FILE_DELETED')
    ),
    CONSTRAINT chk_bank_transfer_proof_review CHECK (
        (status = 'PENDING_REVIEW' AND reviewed_at IS NULL AND reviewed_by_user_id IS NULL
            AND approved_amount IS NULL AND bank_reference IS NULL AND rejection_reason IS NULL)
        OR (status = 'APPROVED' AND reviewed_at IS NOT NULL AND reviewed_by_user_id IS NOT NULL
            AND approved_amount IS NOT NULL AND bank_reference IS NOT NULL AND rejection_reason IS NULL)
        OR (status = 'REJECTED' AND reviewed_at IS NOT NULL AND reviewed_by_user_id IS NOT NULL
            AND approved_amount IS NULL AND bank_reference IS NULL AND rejection_reason IS NOT NULL)
        OR status = 'FILE_DELETED'
    )
);

CREATE UNIQUE INDEX uq_bank_transfer_proofs_reference
    ON bank_transfer_proofs(bank_reference) WHERE bank_reference IS NOT NULL;
CREATE INDEX idx_bank_transfer_proofs_review_queue
    ON bank_transfer_proofs(status, submitted_at, id);
CREATE INDEX idx_bank_transfer_proofs_retention
    ON bank_transfer_proofs(retain_until, id) WHERE storage_key IS NOT NULL;

CREATE TABLE bank_transfer_proof_previews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proof_id UUID NOT NULL REFERENCES bank_transfer_proofs(id) ON DELETE CASCADE,
    preview_index INTEGER NOT NULL CHECK (preview_index >= 0),
    storage_key VARCHAR(36) NOT NULL UNIQUE,
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    sha256 VARCHAR(64) NOT NULL,
    CONSTRAINT uq_bank_transfer_proof_preview_index UNIQUE (proof_id, preview_index)
);

CREATE TABLE email_outbox (
    id UUID PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES customer_orders(id) ON DELETE RESTRICT,
    recipient VARCHAR(254) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    rejection_reason VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    lease_until TIMESTAMPTZ,
    lease_token UUID,
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    CONSTRAINT chk_email_outbox_status CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED')),
    CONSTRAINT uq_email_outbox_order_event UNIQUE (order_id, event_type)
);

CREATE INDEX idx_email_outbox_due
    ON email_outbox(next_attempt_at, created_at) WHERE status IN ('PENDING', 'SENDING');
