CREATE TABLE home_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    eyebrow VARCHAR(100),
    title VARCHAR(150) NOT NULL CHECK (BTRIM(title) <> ''),
    description VARCHAR(1000),
    button_label VARCHAR(100),
    mode VARCHAR(20) NOT NULL CHECK (mode IN ('MANUAL', 'AUTOMATIC')),
    product_limit INTEGER NOT NULL CHECK (product_limit BETWEEN 1 AND 12),
    sort VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_home_sections_display_order UNIQUE (display_order) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT chk_home_sections_sort CHECK (
        (mode = 'MANUAL' AND sort IS NULL)
        OR (mode = 'AUTOMATIC' AND sort IS NOT NULL
            AND sort IN ('NAME_ASC', 'NAME_DESC', 'PRICE_ASC', 'PRICE_DESC', 'NEWEST'))
    )
);

CREATE TABLE home_section_categories (
    section_id BIGINT NOT NULL REFERENCES home_sections(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    PRIMARY KEY (section_id, category_id)
);

CREATE TABLE home_section_products (
    section_id BIGINT NOT NULL REFERENCES home_sections(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    display_order INTEGER NOT NULL CHECK (display_order BETWEEN 0 AND 23),
    CONSTRAINT pk_home_section_products PRIMARY KEY (section_id, product_id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT uq_home_section_products_order UNIQUE (section_id, display_order)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE home_section_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES home_sections(id) ON DELETE CASCADE,
    device VARCHAR(20) NOT NULL CHECK (device IN ('DESKTOP', 'MOBILE')),
    external_url VARCHAR(2048),
    storage_key VARCHAR(36) UNIQUE,
    original_filename VARCHAR(255),
    content_type VARCHAR(50),
    size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_home_section_banners_device UNIQUE (section_id, device),
    CONSTRAINT chk_home_section_banners_source CHECK (
        (external_url IS NOT NULL AND BTRIM(external_url) <> '' AND storage_key IS NULL
            AND original_filename IS NULL AND content_type IS NULL AND size_bytes IS NULL)
        OR
        (external_url IS NULL AND storage_key IS NOT NULL AND original_filename IS NOT NULL
            AND content_type IS NOT NULL AND content_type IN ('image/jpeg', 'image/png')
            AND size_bytes IS NOT NULL AND size_bytes > 0)
    )
);

CREATE INDEX idx_home_section_categories_category ON home_section_categories(category_id);
CREATE INDEX idx_home_section_products_product ON home_section_products(product_id);
CREATE INDEX idx_home_section_banners_section ON home_section_banners(section_id);

WITH inserted AS (
    INSERT INTO home_sections (
        display_order, eyebrow, title, description, button_label, mode, product_limit, sort, is_active
    )
    SELECT 0, 'Periféricos', 'Completá tu setup',
           'Teclados, mouse, auriculares y accesorios para jugar, trabajar y crear con comodidad.',
           'Ver todos los periféricos', 'AUTOMATIC', 12, 'NAME_ASC', TRUE
    WHERE EXISTS (SELECT 1 FROM categories WHERE slug = 'perifericos' AND is_active)
    RETURNING id
)
INSERT INTO home_section_categories (section_id, category_id)
SELECT inserted.id, category.id
FROM inserted
JOIN categories category ON category.slug = 'perifericos' AND category.is_active;

WITH inserted AS (
    INSERT INTO home_sections (
        display_order, eyebrow, title, description, button_label, mode, product_limit, sort, is_active
    )
    SELECT COALESCE((SELECT MAX(display_order) + 1 FROM home_sections), 0),
           'Hardware', 'Potencia para tu equipo',
           'Procesadores, placas de video, memorias y almacenamiento para tu próxima actualización.',
           'Ver catálogo de hardware', 'AUTOMATIC', 12, 'NAME_ASC', TRUE
    WHERE EXISTS (SELECT 1 FROM categories WHERE is_active AND slug <> 'perifericos')
    RETURNING id
)
INSERT INTO home_section_categories (section_id, category_id)
SELECT inserted.id, category.id
FROM inserted
JOIN categories category ON category.is_active AND category.slug <> 'perifericos';

INSERT INTO home_section_banners (section_id, device, external_url)
SELECT id, 'DESKTOP', '/pinatech-banner-perifericos.jpg'
FROM home_sections WHERE title = 'Completá tu setup';

INSERT INTO home_section_banners (section_id, device, external_url)
SELECT id, 'DESKTOP', '/pinatech-banner-hardware.jpg'
FROM home_sections WHERE title = 'Potencia para tu equipo';
