CREATE TABLE home_hero_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_order INTEGER NOT NULL CHECK (display_order BETWEEN 0 AND 4),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    eyebrow VARCHAR(100) NOT NULL CHECK (BTRIM(eyebrow) <> ''),
    title VARCHAR(150) NOT NULL CHECK (BTRIM(title) <> ''),
    accent VARCHAR(150) NOT NULL CHECK (BTRIM(accent) <> ''),
    description VARCHAR(500) NOT NULL CHECK (BTRIM(description) <> ''),
    link VARCHAR(200) NOT NULL CHECK (BTRIM(link) <> ''),
    link_label VARCHAR(100) NOT NULL CHECK (BTRIM(link_label) <> ''),
    show_login_link BOOLEAN NOT NULL DEFAULT FALSE,
    alt_text VARCHAR(200) NOT NULL CHECK (BTRIM(alt_text) <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_home_hero_slides_display_order UNIQUE (display_order) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE home_hero_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_id BIGINT NOT NULL REFERENCES home_hero_slides(id) ON DELETE CASCADE,
    device VARCHAR(20) NOT NULL CHECK (device IN ('DESKTOP', 'MOBILE')),
    storage_key VARCHAR(36) UNIQUE NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(50) NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png')),
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_home_hero_images_slide_device UNIQUE (slide_id, device)
);

CREATE INDEX idx_home_hero_images_slide ON home_hero_images(slide_id);

INSERT INTO home_hero_slides (
    display_order, is_active, eyebrow, title, accent, description, link, link_label, show_login_link, alt_text
) VALUES
    (0, TRUE, 'Pinatech tecnología', 'Elevá tu setup.', 'Elegí con claridad.',
     'Hardware y periféricos con disponibilidad real para armar o actualizar tu equipo.',
     '/catalog', 'Explorar catálogo', TRUE,
     'Pinatech, tecnología a tu alcance, junto a componentes de hardware'),
    (1, TRUE, 'Tu selección te espera', 'No dejes que tu carrito', 'se pierda.',
     'Revisá tus productos, ajustá las cantidades y continuá cuando estés listo.',
     '/cart', 'Ver mi carrito', FALSE,
     'Carrito de compras Pinatech cargado con componentes de hardware');
