import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { AuthService } from '../../core/auth/auth.service';
import { environment } from '../../../environments/environment';

interface Ticket { id:number; customerName:string; technicianName:string; deviceType:string; brand:string; model:string; reportedProblem:string; status:string; priority:string; createdAt:string; }
interface Technician { id:number; name:string; }
const statuses = ['RECEIVED','UNDER_DIAGNOSIS','WAITING_FOR_APPROVAL','APPROVED','IN_REPAIR','WAITING_FOR_PARTS','READY_FOR_PICKUP','DELIVERED','CANCELLED'];

@Component({ imports:[DatePipe,FormsModule,MatFormFieldModule,MatSelectModule], template:`<main><header><p class="eyebrow">Operación técnica</p><h1>Tickets de servicio</h1><p>Seguimiento y actualización de reparaciones en curso.</p></header><section>@for(ticket of tickets();track ticket.id){<article><div><span class="priority" [class.high]="ticket.priority==='HIGH'||ticket.priority==='URGENT'">{{ticket.priority}}</span><strong>#{{ticket.id}} · {{ticket.deviceType}} {{ticket.brand}} {{ticket.model}}</strong><p>{{ticket.customerName}} · {{ticket.reportedProblem}}</p><small>Responsable: {{ticket.technicianName}} · {{ticket.createdAt|date:'medium'}}</small></div><div class="controls"><mat-form-field><mat-label>Estado</mat-label><mat-select [ngModel]="ticket.status" (ngModelChange)="update(ticket,$event)">@for(status of statuses;track status){<mat-option [value]="status">{{status}}</mat-option>}</mat-select></mat-form-field>@if(isAdmin()){<mat-form-field><mat-label>Técnico</mat-label><mat-select [ngModel]="technicianId(ticket)" (ngModelChange)="assign(ticket,$event)">@for(technician of technicians();track technician.id){<mat-option [value]="technician.id">{{technician.name}}</mat-option>}</mat-select></mat-form-field>}</div></article>}@empty{<p>No hay tickets registrados.</p>}</section></main>`,styles:['main{margin:auto;max-width:1100px;padding:3rem 1.5rem}.eyebrow{color:#047857;font-weight:700;text-transform:uppercase}article{align-items:center;border-bottom:1px solid #dfe9e3;display:flex;gap:1rem;justify-content:space-between;padding:1rem 0}article p{color:#52675c;margin:.4rem 0}.controls{display:flex;gap:.5rem}.priority{background:#e7f5ef;border-radius:99px;color:#047857;font-size:.75rem;margin-right:.6rem;padding:.2rem .5rem}.priority.high{background:#fff1f2;color:#be123c}@media(max-width:700px){article,.controls{align-items:start;flex-direction:column}}'],changeDetection:ChangeDetectionStrategy.OnPush })
export class TechnicalComponent { private readonly http=inject(HttpClient); private readonly auth=inject(AuthService); readonly tickets=signal<Ticket[]>([]); readonly technicians=signal<Technician[]>([]); readonly statuses=statuses; readonly isAdmin=()=>this.auth.user()?.roles.includes('ADMIN')??false; constructor(){this.load();if(this.isAdmin())this.http.get<Technician[]>(`${environment.apiBaseUrl}/technical/tickets/technicians`).subscribe(items=>this.technicians.set(items));} load(){this.http.get<Ticket[]>(`${environment.apiBaseUrl}/technical/tickets`).subscribe(items=>this.tickets.set(items));} update(ticket:Ticket,status:string){this.http.patch(`${environment.apiBaseUrl}/technical/tickets/${ticket.id}/status`,{status}).subscribe({next:()=>this.load()});} technicianId(ticket:Ticket){return this.technicians().find(technician=>technician.name===ticket.technicianName)?.id??null;} assign(ticket:Ticket,technicianId:number){this.http.patch(`${environment.apiBaseUrl}/technical/tickets/${ticket.id}/technician`,{technicianId}).subscribe({next:()=>this.load()});} }
