package com.computerstore.order.domain;
import java.math.BigDecimal;
import com.computerstore.catalog.domain.ProductVariant;
import jakarta.persistence.*;
@Entity @Table(name="order_items") public class OrderItem {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="order_id",nullable=false) private CustomerOrder order; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="variant_id",nullable=false) private ProductVariant variant; @Column(name="product_name",nullable=false) private String productName; @Column(name="variant_color_name",nullable=false) private String variantColorName; @Column(name="variant_color_hex") private String variantColorHex; @Column(name="unit_price",nullable=false,precision=19,scale=2) private BigDecimal unitPrice; @Column(nullable=false) private int quantity; @Column(nullable=false,precision=19,scale=2) private BigDecimal subtotal;
 @Column(name="shipping_weight_grams") private Integer shippingWeightGrams; @Column(name="shipping_height_cm") private Integer shippingHeightCm; @Column(name="shipping_width_cm") private Integer shippingWidthCm; @Column(name="shipping_length_cm") private Integer shippingLengthCm; @Column(name="shipping_classification_id") private String shippingClassificationId; @Column(name="shipping_must_keep_vertical") private Boolean mustKeepVertical;
 protected OrderItem(){} public OrderItem(ProductVariant variant,int quantity){this.variant=variant;this.productName=variant.getProduct().getName();this.variantColorName=variant.getColorName();this.variantColorHex=variant.getColorHex();this.unitPrice=variant.getProduct().getPrice();this.quantity=quantity;this.subtotal=unitPrice.multiply(BigDecimal.valueOf(quantity)); if(variant.getProduct().hasCompleteShippingData()){this.shippingWeightGrams=variant.getProduct().getShippingWeightGrams();this.shippingHeightCm=variant.getProduct().getShippingHeightCm();this.shippingWidthCm=variant.getProduct().getShippingWidthCm();this.shippingLengthCm=variant.getProduct().getShippingLengthCm();this.shippingClassificationId=variant.getProduct().getShippingClassificationId().toString();this.mustKeepVertical=variant.getProduct().isMustKeepVertical();}} void setOrder(CustomerOrder order){this.order=order;} public ProductVariant getVariant(){return variant;} public String getProductName(){return productName;} public String getVariantColorName(){return variantColorName;} public String getVariantColorHex(){return variantColorHex;} public BigDecimal getUnitPrice(){return unitPrice;} public int getQuantity(){return quantity;} public BigDecimal getSubtotal(){return subtotal;} public Integer getShippingWeightGrams(){return shippingWeightGrams;} public Integer getShippingHeightCm(){return shippingHeightCm;} public Integer getShippingWidthCm(){return shippingWidthCm;} public Integer getShippingLengthCm(){return shippingLengthCm;} public String getShippingClassificationId(){return shippingClassificationId;} public Boolean getMustKeepVertical(){return mustKeepVertical;}
}
